name: terraform-build

on:

  push:       # or use workflow_dispatch manually
    branches:
      - main
  pull_request:
    branches:
      - main             
      
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}                   

      
jobs:
  terraform:     
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 
      - name: install terraform
        uses: hashicorp/setup-terraform@v3 
      - name: init
        run: terraform init
      - name:  validate
        run:  terraform validate
      - name:  plan 
        run:  terraform plan
        if:  github.event_name == 'pull_request'
      - name: apply
        run: terraform destroy -auto-approve
        if:  github.event_name == 'push' && github.ref == 'refs/heads/main'  

       