on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main        
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "This is  Github actions"
      - name: second
        run: echo "second step" 
      - name: multi-string
        run: |
          ls                     
          pwd
          node -v
  run-windows-commands:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Directory
        run:  Get-location
      - name: Directory using bash
        run: pwd
        shell: bash                  